services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
  litellm:
      image: ghcr.io/berriai/litellm:main-latest
      volumes:
        - ./litellm/litellm-config.yml:/app/config.yaml
        # NOTE: For Google - required auth "GOOGLE_APPLICATION_CREDENTIALS" envronment and volume mount
        # This also means you need to add the `application_default_credentaials.json` file within ~/litellm
        # - ./litellm/application_default_credentials.json:/app/application_default_credentials.json
      ports:
        - "4000:4000"
      command: [ "--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8" ]
      # For Google - see above about required auth "GOOGLE_APPLICATION_CREDENTIALS" envronment and volume mount
      environment:
        # GOOGLE_APPLICATION_CREDENTIALS: /app/application_default_credentials.json  
        - OPENAI_API_KEY=${OPENAI_API_KEY}